/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.text.SimpleDateFormat;
import java.util.Date;
import beans.NotasFiscais;
import conexao.Conexao;
import dao.ClienteDAO;
import dao.NotaDAO;
import dao.ProdutoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;


/**
 *
 * @author pietr
 */
public class Notas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Notas.class.getName());

    /**
     * Creates new form Notas
     */
    public Notas() {
        initComponents(); // Método gerado pelo NetBeans para inicializar os componentes
        
        // Chamando o método para carregar os dados
        carregarComboBoxClientes();
        carregarComboBoxProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCliente = new javax.swing.JComboBox<>();
        cbProdutos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txbSubtotal = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbCliente.setModel(cbCliente.getModel());
        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        cbProdutos.setModel(cbProdutos.getModel());
        cbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdutosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Cliente:");

        jLabel3.setText("Nome Produto");

        jLabel4.setText("Quantidade vendida:");

        txbSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbSubtotalActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código Nota", "Código Cliente", "Código Produto", "Quantidade", "Data"
            }
        ));
        jScrollPane1.setViewportView(tblNotas);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar ao menu");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnListar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnVoltar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalvar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txbSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnLimpar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txbSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnVoltar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void carregarComboBoxClientes() {
        // Lógica para preencher a combo box com os clientes do banco de dados
        NotaDAO notaDAO = new NotaDAO();
        List<String> nomes = notaDAO.listarNomesClientes();
        
        for (String nome : nomes) {
            cbCliente.addItem(nome);
        }
    }  private void carregarComboBoxProdutos() {
        // Lógica para preencher a combo box com os clientes do banco de dados
        NotaDAO notaDAO = new NotaDAO();
        List<String> nomes = notaDAO.listarProdutos();
        
        for (String nome : nomes) {
            cbProdutos.addItem(nome);
        }
    }
    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        String clienteSelecionado = (String) cbCliente.getSelectedItem();
        System.out.println("Cliente selecionado: " + clienteSelecionado);

    }//GEN-LAST:event_cbClienteActionPerformed

    private void cbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdutosActionPerformed
       String clienteSelecionado = (String) cbProdutos.getSelectedItem();
        System.out.println("Produtos selecionado: " + clienteSelecionado);
    }//GEN-LAST:event_cbProdutosActionPerformed

    private void txbSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbSubtotalActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
     // Instancia o objeto Nota Fiscal
    NotasFiscais n = new NotasFiscais();

    // Pega o nome do cliente e busca o ID
    String nomeCliente = (String) cbCliente.getSelectedItem();
    ClienteDAO clienteDAO = new ClienteDAO();
    int codCliente = clienteDAO.buscarIdPorNome(nomeCliente);

    // Pega o nome do produto e busca o ID
    String nomeProduto = (String) cbProdutos.getSelectedItem();
    ProdutoDAO produtoDAO = new ProdutoDAO();
    int codProduto = produtoDAO.buscarIdPorNome(nomeProduto);

    // Verifica se ambos, cliente e produto, foram encontrados
    if (codCliente != -1 && codProduto != -1) {
        // Atribui os códigos à nota fiscal
        n.setCliente(codCliente);
        n.setIdProduto(codProduto);

        try {
            double subtotal = Double.parseDouble(txbSubtotal.getText());
            n.setsubtotal(subtotal);

            // Código para pegar a data atual do sistema
            java.util.Date dataAtual = new java.util.Date();
            java.sql.Timestamp dataTimestamp = new java.sql.Timestamp(dataAtual.getTime());
            n.setData(dataTimestamp);

            // Instancia o NotaDAO e chama o método de inserção
            NotaDAO notaDAO = new NotaDAO();
            notaDAO.inserir(n);

            System.out.println("Nota fiscal salva com sucesso!");

        } catch (NumberFormatException ex) {
            System.err.println("Erro: O subtotal deve ser um número válido.");
        }

    } else {
        System.err.println("Erro ao salvar nota: Cliente e/ou Produto não encontrado(s).");
    }
    limparFormulario();
    }//GEN-LAST:event_btnSalvarActionPerformed
    private void limparFormulario(){
    cbCliente.setSelectedIndex(0);
    cbProdutos.setSelectedIndex(0);
    txbSubtotal.setText("");
    }
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
    // Pega o modelo da tabela e limpa as linhas existentes
    DefaultTableModel modelo = (DefaultTableModel) tblNotas.getModel();
    modelo.setRowCount(0);

    // Consulta SQL para buscar as notas fiscais
    // Adapte o nome da tabela e das colunas conforme sua estrutura no banco de dados
    String sql = "SELECT codNota, codCliente, codProduto, subtotal, dataVenda FROM notasfiscais";

    try (
        Connection conn = Conexao.getConexao();
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        java.sql.ResultSet rs = stmt.executeQuery()
    ) {
        while (rs.next()) {
            // Adiciona as informações da nota fiscal à tabela
            modelo.addRow(new Object[]{
                rs.getInt("codNota"),
                rs.getInt("codCliente"),
                rs.getInt("codProduto"),
                rs.getDouble("subtotal"),
                rs.getTimestamp("dataVenda") // Use getTimestamp() para obter a data e a hora
            });
        }
    } catch (Exception e) {
        // Exibe uma mensagem de erro em uma caixa de diálogo se algo der errado
        JOptionPane.showMessageDialog(this, "Erro ao listar notas fiscais: " + e.getMessage());
    }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       limparFormulario();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Notas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbProdutos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTextField txbSubtotal;
    // End of variables declaration//GEN-END:variables
}
